### ISSUE TITLE
It doesn't pop on desktop

### ISSUE THREAD

**Issue by steinmetz** [HosseinYousefi/yeet#17]
I have been testing your lib on a desktop app and I think it doesn't work properly when I want to pop a page using ``` context.yeet(); ```

Also, the back arrow is not showing by default, so I added it manually:
```
 appBar: AppBar(
              leading: IconButton(icon: Icon(Icons.arrow_back_ios_sharp),
              onPressed: (){
                context.yeet();
              },
     ),
 ), 
```

Thank you!

**Comment by HosseinYousefi** [comment]
@steinmetz can you share your yeet tree? 

I'm asking this because popping works only if you have a `Yeet` inside the children of of another `Yeet`. Like:

```dart
Yeet(
  path: '/hi',
  builder: ...
  children: [
    Yeet(path: '/hi/some/completely/different/path/even', builder: ...),
  ]
),
```

Here if you yeet from `/hi` to `/hi/some/completely/different/path/even` and when you `context.yeet()` it'll go back to `/hi`.

If these two roots are not in subtrees of each other, and for example you want to go from `/a/b/c/d` to `/a/b/c` then you can use `context.yeet('..')`.

**Comment by steinmetz** [comment]
@HosseinYousefi  Thank you for the explanation! I was not using the same root and it was the reason of my problem.

 Thank you again! I will close this issue.
